src/lib.rs

As I can see compiler generate memmove call instead of std::ptr::copy,
so it should be as fast as possible

make copy_bytes_to_start little faster and readable

---

src/lib.rs

Compilation with `cargo build --target=i686-linux-android` failed, because of `char` on arm char is u8 on armeabi, and i8 on i686 or vise versa.

fix build with --target=i686-linux-android: *const i8 != *const u8

---

src/lib.rs

Reverting until the change is better explained. See #4.

Revert "add log4rs support" temporarily.

---

src/lib.rs

- Re-revert `add log4rs support`.
- Rename `PlatformLogger` to `AndroidLogger`.
- Some basic docs.

Reexpose internal logger

---

.travis.yml
Cargo.toml
README.md

To prevent things like fixed in d59a22ae3a33a4a0c11098fa6d1f317c734c110b test build with all supported by rustup targets. Also budges from CI in theory (potentially) may icrease package raiting.
Note: in README.md url should be fixed to point travis-ci for  Nercury/android_logger-rs instead of my fork.

check at least that we have no problem with syntax

---

Cargo.toml
src/lib.rs

Hi!
I had a go this morning at implementing #30 and I ended up changing quite a few things.
This breaks the API and I would understand if you don't want to merge it.
Here's what I've done

use env_logger filter

---

src/lib.rs

Our application uses [fern](https://crates.io/crates/fern) to log to multiple sinks and filter out various crates. The application is now being ported to Android, and it to log to Logcat, it'd be nice to use this crate's logger. But there's an issue with this crate - even though a `Config` is exposed to configure a `AndroidLogger` instance, there's no way to construct an `AndroidLogger` instance with a specific configuration. This PR changes that so an `AndroidLogger` can be constructed from the config.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/nercury/android_logger-rs/32)

Allow constructing new instances of a logger with a config.

---

Cargo.toml

env_logger comes with several optional-but-default-activated features,
including a dependency on regex.
There's no need for android_logger to require that. Deactivating default
features allows users of android_logger to define the features they
need.
<details>
We're using regex in our own library, but with [recent changes](https://github.com/rust-lang/regex/pull/613) we were able to reduce our library size by 30% or so. However, now upgrading to the latest android_logger pulls in the whole of regex again, without a way to prevent that. If android_logger just won't ask for the default features our own library is free to specify the final feature set (of course only as long as no _other_ library also pulls in regex with default features).
</details>

Don't activate default features of env_logger

---

Cargo.toml

This is a breaking change since this crate exposes `env_logger` types publicly. But it would be good to migrate to the newer breaking release of `env_logger`. Allows users of this crate to use the latest `env_logger` without depending on two versions.

Upgrade env_logger dependency to 0.8.2

---

Cargo.toml
src/lib.rs

This helps reduce overhead when fast bursts of logging occur and in general models what it actually does better. The logic only let a caller init the global logger once since it used `log::set_logger` but used a `RwLock` that never called `.write()` more than once.
Happy to drop the Clippy lint commit if you don't care for it.

Remove logger config locking

---

src/lib.rs

This allows for better ergonomics for users that want to use the PlatformLogWriter without using the `log` crate directly, e.g. when using another logging framework to log (like slog). Without this, callers need to first map to a log::Level instead of directly mapping to Android priorities.

allow creating a PlatformLogWriter directly from a priority

---

Cargo.toml

env_logger replaced dependencies itself which have a dubious security track record or other issues. Other than that MSRV has been raised to 1.60.

Bump env_logger minor version from 0.9 to 0.10

---

.github/workflows/ci.yml
src/lib.rs

Fixes #58 
Additionally, reworks CI pipeline:
- runs checks for `--target ${{ matrix.target }}`
- switches to `dtolnay/rust-toolchain` action (`actions-rs` seems to be somewhat [deprecated](https://github.com/actions-rs/toolchain/issues/216))

Fix compilation for Android targets

---

CHANGELOG.md
README.md
src/lib.rs
tests/config_log_level.rs
tests/multiple_init.rs

The document says that if `Warn` is set, `Error` will also be logged, but not `Info`. But in fact, if `Warn` is set, only `Warn` is logged, not `Error`.
I think this is a bug caused by the comparison operator.

Fix bug only values equal to the set level are logged

---

CHANGELOG.md
Cargo.toml
src/lib.rs

Rebased version of #50 
* Add `LogId` enum to identify the different log buffers.
* Add an argument to `PlatformLogWriter::new` to allow a target buffer to be specified.
* Update `Config` to allow specifying a target buffer.

rebase: Support selecting target buffer

---

CHANGELOG.md
src/lib.rs

As per user report at least SDKv26 does not resolve LOG_ID_DEFAULT to LOG_ID_MAIN internally, which forces users to set LOG_ID_MAIN explicitly.
Rework android_log function to accept optional buf_id and use __android_log_write FFI function if no buf_id specified. This will return previous behavior for users that do not need to override buf_id.
Closes: https://github.com/Nercury/android_logger-rs/issues/66
Fixes: fee1beabd33e ("Support selecting target buffer of Android logging system")

Fix buf_id issues with older SDK API version

---

Cargo.toml
src/lib.rs

I've also updated the edition to 2021, because our dependencies have an MSRV of (at least) 1.71 - [env_logger](https://github.com/rust-cli/env_logger/blob/8962096976b0fa9c05b8b5ba5251861d60abf943/Cargo.toml#L8), for example

Update env_logger to 0.11

---

Cargo.toml
src/lib.rs

our MSVR at least 1.71.0, and once_cell was merge into std in 1.70.0, so there are no reason to use external one instead of std

remove once_cell as dependency

---

Cargo.toml

Also moved `env_filter` to a separate section for consistency.
Fixes #73

Fix regex dependencies getting pulled unexpectedly

---

Cargo.toml

Fixes #76
Even though a lot of `cfg` make it possible to compile this Android-specific crate on non-Android platforms, only seeing non-Android platforms inside the docs.rs platform dropdown appears a bit strange.
Instead, build the documentation for every Android platform listed at https://doc.rust-lang.org/rustc/platform-support/android.html, which might also result in better intradoc links to specific types provided by `std`.

Only provide docs.rs pages for Android targets

---

Cargo.toml

Since this crate provides access/interop to an Android-specific (OS) API, use the new `os::android-apis` category that I recently upstreamed at https://github.com/rust-lang/crates.io/pull/8558.  That'll make this crate show up at https://crates.io/categories/os::android-apis going forward.

cargo: Add `os::android-apis` category

---

src/lib.rs

The currently hard-coded limit is 23 characters. This limit originates from the pre-Android 7.0 32-character limit on system property names, because Android's `liblog` allows setting the log level at runtime through `log.tag` system properties [1]. The limit meant that "log.tag.SOMETAG" must have been shorter than 32 bytes, leaving 23 bytes for the tag itself.
The system property length limitation was removed in [2], so since 2017 it no longer applies, and some Android components already use longer tags [3][4].
This change increases the size of the stack-allocated buffer used for null-terminating the tag to 128 bytes, and adds support for even longer tags by falling back to heap-allocated CString when the tag is longer than that. The fallback path will introduce a performance penalty, but …

Prevent truncating log tag name

---

src/lib.rs

For https://github.com/rust-mobile/android_logger-rs/pull/81#discussion_r1745215208
`CStr::from_ptr()` is `unsafe` because it reads a raw pointer, and searches for a terminating nul character in the pointed region of memory.
This is unnecessary as both calls already initialize a given number of characters and terminate with a nul, allowing us to pass a sized and initialized slice (without casting `*const MaybeUninit<u8>` to `*const u8`) directly to `CStr::from_bytes_with_nul()` (available since Rust 1.10, unlike `CStr::from_bytes_until_nul()` which was only stabilized in 1.69).  Unfortunately all `std` helper APIs to initialize slices of `MaybeUninit` are still unstable, making this less ideal to write at the moment.

Replace `CStr::from_ptr()` with `CStr::from_bytes_with_nul()`

---

src/lib.rs

Closes #79
Allows these structs to be printed, useful for supposedly the `log4rs` crate which requires this to be implemented on `AndroidLogger`.

Derive/implement `Debug` for `Config` and `AndroidLogger`

---

.github/workflows/ci.yml
src/config.rs

Note that the `style_format` setting in `rustfmt.toml` would default to `edition` in `Cargo.toml`, but that's still on `2021` while `2024` already generates a bit nicer formatted code so this file is left in place.

ci: Run `cargo fmt --check` to ensure code is always properly formatted

---

.github/workflows/ci.yml
Cargo.toml
README.md
src/config.rs
src/lib.rs
src/platform_log_writer.rs

Android's C logging API determines the effective log level based on a combination [1] of a global variable, system-wide properties [2], and call-specific default. log + android_logger crates add another layer of log filtering on top of that, independent from the C API.
```
.-----.
| app |
'-----'
|
v
.-----------.   filter by STATIC_MAX_LEVEL [3] +
| log crate | - MAX_LOG_LEVEL_FILTER [4],
'-----------'   overrideable via log::set_max_level
|
v
.----------------------.
| android_logger crate | - filter by Config::max_level [5]
'----------------------'
|
v
.--------.
| liblog | - filter by global state or system-wide properties [2]
'--------'
```
The result is that in mixed C/C++ + Rust applications, logs originating from Rust use the least verbose level configured, which sometimes results …

Use __android_log_is_loggable in AndroidLogger::enabled

---

README.md
examples/system_log_level_overrides.rs

Pull https://github.com/dextero/log-test into this repon as an example, as suggested by @MarijnS95 on #84.
Also add a link to `log::set_max_level` from README, as suggested on the same PR.

Add examples/system_log_level_overrides.rs

---

src/platform_log_writer.rs

Some crates use log crate with a message padded with a number of nullbytes [1]. This currently causes panics.
Using `CStr::from_bytes_until_nul` accepts multiple null-bytes, and instead stops at the first nullbyte in a buffer.
This may truncate some logs with text interspersed with nullbytes. However, I'd say logging _something_ there is a less-bad option than crashing just because we got a nullbyte in the &str.
[1] https://github.com/cloudflare/quiche/blob/d0efd2c5278b9dbe8d6544c3015f8c772f3513b4/quiche/src/tls/mod.rs#L1040

Avoid panic on buffers with embedded nul bytes
